#setup vault with ansible.

- name: Set prompt
  ansible.builtin.shell: set-prompt vault

- name: Download Vault repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: latest

- name: Start Vault service
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: yes