
#we are running a job that will checkout the code and initiate terraform

name: Provision Tool Infra
on: [push, workflow_dispatch]
jobs:
  Provision:
    runs-on: ubuntu-latest #github provides its own runner (running on ubuntu)
    steps:
      - uses: actions/checkout@v4 #used to checkout the code
      - run: terraform init