
# runs a job that will checkout the code and initiate terraform

name: Provision Tool Infra
on: [workflow_dispatch] # manual trigger
jobs:
  Provision:
    runs-on: self-hosted # build server
    steps:
      - uses: actions/checkout@v4 # get the code
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve