#setup vault

jobs:
  Provision:
    runs-on: self-hosted #setting up workflow to run on self-hosted server
    steps:
      - uses: actions/checkout@v4 #used to checkout the code
      - name: Run Vault Setup
        run: ansible-playbook -i vault-internal.sridevops.site, tool-setup.yml -e ansible_user=ec2-user -e ansible_password=DevOps321 -e tool_name=vault